default_context:
  project_name: 'face-to-face-voting-web'
  project_slug: 'face-to-face-voting-web'
  domain_main: 'vote.mirea.ninja'
  domain_staging: 'stag.vote.mirea.ninja'
  docker_swarm_stack_name_main: 'vote-mirea-ninja'
  docker_swarm_stack_name_staging: 'stag-vote-mirea-ninja'
  secret_key: 'K1TeOMZiNN'
  first_superuser: 'admin@vote.mirea.ninja'
  first_superuser_password: 'BG9fOQSI3S'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.vote.mirea.ninja", "https://stag.vote.mirea.ninja", "https://vote.mirea.ninja", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@vote.mirea.ninja'
  postgres_password: 'Vw5fyFGWz8'
  pgadmin_default_user: 'admin@vote.mirea.ninja'
  pgadmin_default_user_password: 'BG9fOQSI3S'
  traefik_constraint_tag: 'vote.mirea.ninja'
  traefik_constraint_tag_staging: 'stag.vote.mirea.ninja'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:BG9fOQSI3S'
  sentry_dsn: 'https://678117601ff44fcbac95a79b462f70a2@o593970.ingest.sentry.io/6325605'
  docker_image_prefix: 'mireaninja'
  docker_image_backend: 'mireaninja_backend'
  docker_image_celeryworker: 'mireaninja_celeryworker'
  docker_image_frontend: 'mireaninja_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
