"""empty message

Revision ID: 0655c37c8555
Revises: 08802ebc63f8
Create Date: 2022-04-12 16:06:23.422400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0655c37c8555'
down_revision = '08802ebc63f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_events_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderator_events_association')
    # ### end Alembic commands ###
