"""empty message

Revision ID: 08802ebc63f8
Revises: 328663bc1b59
Create Date: 2022-04-12 16:01:33.552982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08802ebc63f8'
down_revision = '328663bc1b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
