"""empty message

Revision ID: 1e6d2a5e1765
Revises: acf138918aba
Create Date: 2022-04-16 08:25:19.534767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6d2a5e1765'
down_revision = 'acf138918aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
