"""empty message

Revision ID: 328663bc1b59
Revises: 849c82b585e7
Create Date: 2022-04-12 16:00:46.711296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328663bc1b59'
down_revision = '849c82b585e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
