"""empty message

Revision ID: 4176bd0d2b77
Revises: e07ddf79599d
Create Date: 2022-04-19 18:32:17.793035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4176bd0d2b77'
down_revision = 'e07ddf79599d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('is_running', sa.Boolean(), nullable=True))
    op.drop_column('poll', 'is_poll_running')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('is_poll_running', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('poll', 'is_running')
    # ### end Alembic commands ###
