"""empty message

Revision ID: 669cb795257e
Revises: 4176bd0d2b77
Create Date: 2022-04-19 22:07:32.809084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669cb795257e'
down_revision = '4176bd0d2b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer_option_id', sa.Integer(), nullable=True))
    op.drop_index('ix_answer_text', table_name='answer')
    op.create_foreign_key(None, 'answer', 'answer', ['answer_option_id'], ['id'])
    op.drop_column('answer', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_index('ix_answer_text', 'answer', ['text'], unique=False)
    op.drop_column('answer', 'answer_option_id')
    # ### end Alembic commands ###
