"""empty message

Revision ID: 7560471b0a4d
Revises: 1e6d2a5e1765
Create Date: 2022-04-17 16:54:19.658336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7560471b0a4d'
down_revision = '1e6d2a5e1765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
