"""empty message

Revision ID: 7bc4c698cf10
Revises: db41c0246df4
Create Date: 2022-04-13 18:16:02.466089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc4c698cf10'
down_revision = 'db41c0246df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
