"""Update events

Revision ID: 849c82b585e7
Revises: 92df1bd1d55a
Create Date: 2022-04-12 15:25:19.645045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849c82b585e7'
down_revision = '92df1bd1d55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('event_creator_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['owner_id'], ['id'])
    op.drop_column('event', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_creator_id_fkey', 'event', 'user', ['creator_id'], ['id'])
    op.drop_column('event', 'owner_id')
    # ### end Alembic commands ###
