"""Update Events ref

Revision ID: 92df1bd1d55a
Revises: ea8e2ea9c305
Create Date: 2022-04-12 14:58:32.977654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92df1bd1d55a'
down_revision = 'ea8e2ea9c305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
