"""empty message

Revision ID: acf138918aba
Revises: 7bc4c698cf10
Create Date: 2022-04-13 18:19:47.479129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf138918aba'
down_revision = '7bc4c698cf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_id'), 'poll', ['id'], unique=False)
    op.create_index(op.f('ix_poll_question'), 'poll', ['question'], unique=False)
    op.create_table('accesslog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('given_by_id', sa.Integer(), nullable=True),
    sa.Column('received_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['given_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['received_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesslog_id'), 'accesslog', ['id'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    op.create_index(op.f('ix_answer_text'), 'answer', ['text'], unique=False)
    op.create_table('answeroption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answeroption_id'), 'answeroption', ['id'], unique=False)
    op.create_index(op.f('ix_answeroption_text'), 'answeroption', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answeroption_text'), table_name='answeroption')
    op.drop_index(op.f('ix_answeroption_id'), table_name='answeroption')
    op.drop_table('answeroption')
    op.drop_index(op.f('ix_answer_text'), table_name='answer')
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_accesslog_id'), table_name='accesslog')
    op.drop_table('accesslog')
    op.drop_index(op.f('ix_poll_question'), table_name='poll')
    op.drop_index(op.f('ix_poll_id'), table_name='poll')
    op.drop_table('poll')
    # ### end Alembic commands ###
