"""empty message

Revision ID: e07ddf79599d
Revises: 7560471b0a4d
Create Date: 2022-04-19 15:55:32.191962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07ddf79599d'
down_revision = '7560471b0a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('event', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('close_at', sa.DateTime(), nullable=True))
    op.add_column('poll', sa.Column('is_poll_running', sa.Boolean(), nullable=True))
    op.add_column('poll', sa.Column('stop_at', sa.DateTime(), nullable=True))
    op.add_column('poll', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'poll', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll', type_='foreignkey')
    op.drop_column('poll', 'event_id')
    op.drop_column('poll', 'stop_at')
    op.drop_column('poll', 'is_poll_running')
    op.drop_column('event', 'close_at')
    op.drop_column('event', 'start_at')
    op.drop_column('event', 'created_at')
    op.drop_column('event', 'is_open')
    # ### end Alembic commands ###
